# Generated by Django 3.1.1 on 2020-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20201103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/'),
        ),
    ]
